"use client";
import { useActionState } from "react";
import { SUPPORTED_CURRENCIES } from "@/features/auth/options";
import { createLegAction, updateLegAction } from "../actions";
import { initialRouteActionState, LEG_STATUSES, TRAVEL_MODES, type LegFormValues } from "../types";
import { IANA_TIMEZONES } from "../timezones";
const labels={plane:"Avião",train:"Comboio",bus:"Autocarro",car:"Carro",ferry:"Ferry",other:"Outro"};const statuses={planned:"Planeado",booked:"Reservado",paid:"Pago",cancelled:"Cancelado",completed:"Concluído"};const input="h-12 w-full rounded-control border border-input bg-card px-4";
export function LegForm({tripId,legId,initial,fromLabel,toLabel,currency}:{tripId:string;legId?:string;initial:LegFormValues;fromLabel:string;toLabel:string;currency:string}){const action=legId?updateLegAction.bind(null,tripId,legId):createLegAction.bind(null,tripId);const[state,formAction,pending]=useActionState(action,{...initialRouteActionState,values:initial});const v=state.values&&"fromToken" in state.values?state.values:initial;return <form key={JSON.stringify(v)} action={formAction} className="space-y-6" noValidate><input type="hidden" name="fromToken" value={v.fromToken}/><input type="hidden" name="toToken" value={v.toToken}/><input type="hidden" name="createRequestId" value={v.createRequestId}/><p className="rounded-control bg-muted p-4 font-medium">{fromLabel} → {toLabel}</p>
 <div className="grid gap-5 sm:grid-cols-2"><Select name="mode" label="Modo" value={v.mode} options={TRAVEL_MODES.map(x=>[x,labels[x]])}/><Select name="status" label="Estado" value={v.status} options={LEG_STATUSES.map(x=>[x,statuses[x]])}/></div>
 <DateTime side="departure" title="Partida" v={v} errors={state.fieldErrors}/><DateTime side="arrival" title="Chegada" v={v} errors={state.fieldErrors}/>
 <div className="grid gap-5 sm:grid-cols-2"><Field name="operator" label="Operador (opcional)" value={v.operator}/><Field name="reference" label="Referência (opcional)" value={v.reference}/></div>
 {v.priceCurrency&&v.priceCurrency!==currency?<div className="grid gap-5 sm:grid-cols-2"><Field name="priceAmount" label="Valor da passagem (opcional)" value={v.priceAmount} error={state.fieldErrors?.priceAmount}/><div><label className="mb-2 block text-sm font-medium" htmlFor="priceCurrency">Moeda</label><select className={input} id="priceCurrency" name="priceCurrency" defaultValue={v.priceCurrency}>{SUPPORTED_CURRENCIES.map(c=><option key={c}>{c}</option>)}</select><p className="mt-1 text-xs text-muted-foreground">Só valores em {currency} entram automaticamente nos gastos.</p></div></div>
 :<div><input type="hidden" name="priceCurrency" value={currency}/><Field name="priceAmount" label={`Valor da passagem (${currency}, opcional)`} value={v.priceAmount} error={state.fieldErrors?.priceAmount} inputMode="decimal" placeholder="0,00"/><p className="mt-1 text-xs text-muted-foreground">É adicionado automaticamente aos gastos, na categoria Transportes. Com o estado “Pago”, fica marcado como pago.</p></div>}
 <div><label className="mb-2 block text-sm font-medium" htmlFor="notes">Notas (opcional)</label><textarea className="w-full rounded-control border border-input p-4" rows={4} id="notes" name="notes" defaultValue={v.notes}/></div>{state.message?<p role="alert" className="rounded-control border border-destructive bg-destructive-muted p-4 text-sm text-destructive">{state.message}</p>:null}<button disabled={pending} className="rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-60">{pending?"A guardar…":legId?"Guardar transporte":"Adicionar transporte"}</button></form>}
function Field({name,label,value,error,inputMode,placeholder}:{name:string;label:string;value:string;error?:string;inputMode?:"decimal";placeholder?:string}){const type=name.endsWith("Date")?"date":name.endsWith("Time")?"time":"text";return <div><label className="mb-2 block text-sm font-medium" htmlFor={name}>{label}</label><input type={type} className={input} id={name} name={name} defaultValue={value} inputMode={inputMode} placeholder={placeholder} aria-invalid={Boolean(error)}/>{error?<p className="mt-1 text-sm text-destructive">{error}</p>:null}</div>}
function Select({name,label,value,options}:{name:string;label:string;value:string;options:(readonly[string,string])[]}){return <div><label className="mb-2 block text-sm font-medium" htmlFor={name}>{label}</label><select className={input} id={name} name={name} defaultValue={value}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div>}
function DateTime({side,title,v,errors}:{side:"departure"|"arrival";title:string;v:LegFormValues;errors?:Record<string,string>}){const d=`${side}Date` as const,t=`${side}Time` as const,z=`${side}Timezone` as const;return <fieldset><legend className="mb-3 font-semibold">{title} (opcional)</legend><div className="grid gap-4 sm:grid-cols-3"><Field name={d} label="Data" value={v[d]} error={errors?.[d]}/><Field name={t} label="Hora" value={v[t]} error={errors?.[t]}/><div><label className="mb-2 block text-sm font-medium" htmlFor={z}>Timezone (opcional)</label><select className={input} id={z} name={z} defaultValue={v[z]}><option value="">Sem timezone</option>{IANA_TIMEZONES.map(timezone=><option key={timezone} value={timezone}>{timezone}</option>)}</select>{errors?.[z]?<p className="mt-1 text-sm text-destructive">{errors[z]}</p>:null}</div></div></fieldset>}
