"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { z } from "zod";
import { SUPPORTED_CURRENCIES } from "@/features/auth/options";
import { parseMoneyToMinorUnits } from "@/features/trips/money";
import { getOwnedTrip, requireTripUser } from "@/features/trips/queries";
import { buildRoutePoints, parseRoutePointToken, validateStopSequence } from "./route-model";
import { getOwnedLeg, getOwnedRoute, getOwnedStop } from "./queries";
import { legSchema, legValues, stopSchema, stopValues, uuidSchema } from "./schemas";
import type { LegFormValues, RouteActionState, Stop, StopFormValues } from "./types";

function errors(error:z.ZodError){const result:Record<string,string>={}; for(const issue of error.issues){const key=String(issue.path[0]??""); if(key&&!result[key])result[key]=issue.message;} return result;}
function path(tripId:string){return `/trips/${tripId}/route`;}
function revalidateTrip(tripId:string){revalidatePath(`/trips/${tripId}`,"layout");}
function nullable(value:string|null){return value || null;}

export async function createStopAction(tripId:string,_previous:RouteActionState,data:FormData):Promise<RouteActionState>{
  const values=stopValues(data), parsed=stopSchema.safeParse(values), id=uuidSchema.safeParse(tripId);
  if(!id.success)return{status:"error",message:"Viagem não encontrada.",values}; if(!parsed.success)return{status:"error",fieldErrors:errors(parsed.error),values};
  const [trip,route]=await Promise.all([getOwnedTrip(tripId),getOwnedRoute(tripId)]); if(!trip||!route)return{status:"error",message:"Viagem não encontrada.",values};
  if(parsed.data.arrivalDate<trip.startDate||parsed.data.departureDate>trip.endDate)return{status:"error",message:"As datas do destino devem ficar dentro das datas da viagem.",values};
  const position=route.stops.filter(stop=>stop.departureDate<=parsed.data.arrivalDate).length+1;const candidate:Stop={id:"candidate",tripId,position,placeName:parsed.data.placeName,countryCode:parsed.data.countryCode,countryName:parsed.data.countryName,arrivalDate:parsed.data.arrivalDate,departureDate:parsed.data.departureDate,timezone:parsed.data.timezone,notes:parsed.data.notes,createdAt:"",updatedAt:""};
  const conflict=validateStopSequence([...route.stops.map(stop=>stop.position>=position?{...stop,position:stop.position+1}:stop),candidate]); if(conflict)return{status:"error",message:conflict,values};
  const {supabase}=await requireTripUser(); const args={p_trip_id:tripId,p_place_name:parsed.data.placeName,p_country_code:parsed.data.countryCode,p_country_name:parsed.data.countryName,p_arrival_date:parsed.data.arrivalDate,p_departure_date:parsed.data.departureDate,p_timezone:parsed.data.timezone,p_notes:parsed.data.notes,p_request_id:parsed.data.createRequestId}; const {data:stopId,error}=position>route.stops.length?await supabase.rpc("create_route_stop",args):await supabase.rpc("create_route_stop_at",{...args,p_position:position}); if(error?.code==="PGRST202")return{status:"error",message:"Para inserir um destino entre outros, aplique primeiro a migração 202610050012_insert_route_stop.sql no Supabase.",values};
  if(error||!stopId)return{status:"error",message:"Não foi possível adicionar o destino. Verifique as datas e tente novamente.",values}; revalidateTrip(tripId); redirect(`${path(tripId)}?destinationAdded=1`);
}

export async function updateStopAction(tripId:string,stopId:string,_previous:RouteActionState,data:FormData):Promise<RouteActionState>{
  const values=stopValues(data),parsed=stopSchema.safeParse(values); if(!uuidSchema.safeParse(tripId).success||!uuidSchema.safeParse(stopId).success)return{status:"error",message:"Destino não encontrado.",values}; if(!parsed.success)return{status:"error",fieldErrors:errors(parsed.error),values};
  const [trip,route,stop]=await Promise.all([getOwnedTrip(tripId),getOwnedRoute(tripId),getOwnedStop(tripId,stopId)]); if(!trip||!route||!stop)return{status:"error",message:"Destino não encontrado.",values};
  if(parsed.data.arrivalDate<trip.startDate||parsed.data.departureDate>trip.endDate)return{status:"error",message:"As datas do destino devem ficar dentro das datas da viagem.",values};
  const next={...stop,...parsed.data}; const conflict=validateStopSequence(route.stops.map((item)=>item.id===stopId?next:item)); if(conflict)return{status:"error",message:conflict,values};
  const incoming=route.legs.find((leg)=>leg.toStopId===stopId&&!leg.reviewRequired&&leg.status!=="cancelled"); const outgoing=route.legs.find((leg)=>leg.fromStopId===stopId&&!leg.reviewRequired&&leg.status!=="cancelled");
  if(incoming?.arrivalDate&&incoming.arrivalDate>parsed.data.arrivalDate)return{status:"error",message:"A chegada do transporte associado ocorre depois da nova chegada ao destino.",values};
  if(outgoing?.departureDate&&outgoing.departureDate<parsed.data.departureDate)return{status:"error",message:"A partida do transporte associado ocorre antes da nova saída do destino.",values};
  const {supabase,user}=await requireTripUser(); const {data:saved,error}=await supabase.from("stops").update({place_name:parsed.data.placeName,country_code:parsed.data.countryCode,country_name:parsed.data.countryName,arrival_date:parsed.data.arrivalDate,departure_date:parsed.data.departureDate,timezone:parsed.data.timezone,notes:parsed.data.notes}).eq("id",stopId).eq("trip_id",tripId).select("id").maybeSingle(); void user;
  if(error||!saved)return{status:"error",message:"Não foi possível guardar o destino.",values}; revalidateTrip(tripId); redirect(`${path(tripId)}?destinationUpdated=1`);
}

export async function reorderStopsAction(tripId:string,_previous:RouteActionState,data:FormData):Promise<RouteActionState>{
  let ids:unknown; try{ids=JSON.parse(String(data.get("stopIds")??"[]"));}catch{return{status:"error",message:"Ordem inválida."};}
  if(!Array.isArray(ids)||ids.some((id)=>!uuidSchema.safeParse(id).success))return{status:"error",message:"Ordem inválida."};
  const route=await getOwnedRoute(tripId); if(!route)return{status:"error",message:"Viagem não encontrada."}; const byId=new Map(route.stops.map((stop)=>[stop.id,stop])); const ordered=ids.map((id)=>byId.get(String(id))).filter((stop):stop is Stop=>Boolean(stop)).map((stop,index)=>({...stop,position:index+1})); const conflict=validateStopSequence(ordered); if(conflict)return{status:"error",message:conflict};
  const {supabase}=await requireTripUser(); const {error}=await supabase.rpc("reorder_route_stops",{p_trip_id:tripId,p_stop_ids:ids}); if(error)return{status:"error",message:"Não foi possível guardar a nova ordem. A rota anterior foi preservada."}; revalidateTrip(tripId); redirect(`${path(tripId)}?routeReordered=1`);
}

export async function deleteStopAction(tripId:string,stopId:string,_previous:RouteActionState,data:FormData):Promise<RouteActionState>{
  const stop=await getOwnedStop(tripId,stopId); if(!stop)return{status:"error",message:"Destino não encontrado."}; if(String(data.get("confirmation")??"")!==stop.placeName)return{status:"error",message:"Escreva o nome exato do destino para confirmar."};
  const {supabase}=await requireTripUser(); const {error}=await supabase.rpc("delete_route_stop",{p_trip_id:tripId,p_stop_id:stopId}); if(error)return{status:"error",message:error.code==="23503"?"Este destino tem histórico financeiro associado. Reassocie esses registos antes de eliminar; nada foi apagado.":"Não foi possível eliminar o destino. A rota não foi alterada."}; revalidateTrip(tripId); redirect(`${path(tripId)}?destinationDeleted=1`);
}

function legPayload(parsed:z.infer<typeof legSchema>,reviewRequired=false){const from=parseRoutePointToken(parsed.fromToken)!,to=parseRoutePointToken(parsed.toToken)!; const currency=parsed.priceCurrency as (typeof SUPPORTED_CURRENCIES)[number]; return{from_kind:from.kind,from_stop_id:from.stopId,to_kind:to.kind,to_stop_id:to.stopId,mode:parsed.mode,status:parsed.status,departure_date:nullable(parsed.departureDate),departure_time:nullable(parsed.departureTime),departure_timezone:nullable(parsed.departureTimezone),arrival_date:nullable(parsed.arrivalDate),arrival_time:nullable(parsed.arrivalTime),arrival_timezone:nullable(parsed.arrivalTimezone),operator:parsed.operator,reference:parsed.reference,price_minor:parsed.priceAmount?parseMoneyToMinorUnits(parsed.priceAmount,currency)?.toString():null,price_currency:parsed.priceAmount?currency:null,notes:parsed.notes,review_required:reviewRequired};}
async function validateEndpoints(tripId:string,values:LegFormValues){const [trip,route]=await Promise.all([getOwnedTrip(tripId),getOwnedRoute(tripId)]); if(!trip||!route)return false; const points=buildRoutePoints(trip,route.stops); return points.some((point,index)=>point.token===values.fromToken&&points[index+1]?.token===values.toToken);}

export async function createLegAction(tripId:string,_previous:RouteActionState,data:FormData):Promise<RouteActionState>{const values=legValues(data),parsed=legSchema.safeParse(values); if(!parsed.success)return{status:"error",fieldErrors:errors(parsed.error),values}; if(!parseRoutePointToken(parsed.data.fromToken)||!parseRoutePointToken(parsed.data.toToken)||!await validateEndpoints(tripId,values))return{status:"error",message:"Os pontos selecionados já não são adjacentes. Atualize a rota.",values}; const {supabase,user}=await requireTripUser(); const {data:saved,error}=await supabase.from("travel_legs").insert({trip_id:tripId,...legPayload(parsed.data),create_request_id:parsed.data.createRequestId}).select("id").maybeSingle(); void user; if(error?.code==="23505"){const{data:existing}=await supabase.from("travel_legs").select("id").eq("trip_id",tripId).eq("create_request_id",parsed.data.createRequestId).maybeSingle();if(existing?.id)redirect(`${path(tripId)}?transportAdded=1`);}if(error||!saved)return{status:"error",message:"Não foi possível guardar o transporte. Verifique horários e transporte ativo existente.",values}; revalidateTrip(tripId); redirect(`${path(tripId)}?transportAdded=1`);}
export async function updateLegAction(tripId:string,legId:string,_previous:RouteActionState,data:FormData):Promise<RouteActionState>{const values=legValues(data),parsed=legSchema.safeParse(values); if(!parsed.success)return{status:"error",fieldErrors:errors(parsed.error),values}; const current=await getOwnedLeg(tripId,legId); if(!current)return{status:"error",message:"Transporte não encontrado.",values}; const adjacent=await validateEndpoints(tripId,values);if(!adjacent&&!(current.reviewRequired&&parsed.data.status==="cancelled"))return{status:"error",message:"Estes pontos já não são adjacentes. Marque o registo como cancelado ou elimine-o.",values}; const {supabase,user}=await requireTripUser(); const {data:saved,error}=await supabase.from("travel_legs").update(legPayload(parsed.data,!adjacent)).eq("id",legId).eq("trip_id",tripId).select("id").maybeSingle(); void user;if(error||!saved)return{status:"error",message:"Não foi possível guardar o transporte.",values};revalidateTrip(tripId);redirect(`${path(tripId)}?transportUpdated=1`);}
export async function deleteLegAction(tripId:string,legId:string,_previous:RouteActionState,data:FormData):Promise<RouteActionState>{const leg=await getOwnedLeg(tripId,legId);if(!leg)return{status:"error",message:"Transporte não encontrado."};if(String(data.get("confirmation")??"")!=="ELIMINAR")return{status:"error",message:"Escreva ELIMINAR para confirmar."};const{supabase,user}=await requireTripUser();const{data:deleted,error}=await supabase.from("travel_legs").delete().eq("id",legId).eq("trip_id",tripId).select("id").maybeSingle();void user;if(error||!deleted)return{status:"error",message:error?.code==="23503"?"Este transporte tem histórico financeiro associado. Reassocie esses registos antes de eliminar; nada foi apagado.":"Não foi possível eliminar o transporte."};revalidateTrip(tripId);redirect(`${path(tripId)}?transportDeleted=1`);}
