import { readFileSync } from "node:fs";import { describe,expect,it } from "vitest";
const sql=readFileSync("supabase/migrations/202609010010_create_documents.sql","utf8");const actions=readFileSync("features/documents/actions.ts","utf8");const forms=readFileSync("features/documents/components/forms.tsx","utf8");const download=readFileSync("app/(app)/trips/[tripId]/documents/[documentId]/download/route.ts","utf8");
describe("document security contract",()=>{
  it("uses a private constrained bucket and owner-scoped RLS",()=>{expect(sql).toContain("alter table public.travel_documents enable row level security");expect(sql).toContain("trips.user_id=(select auth.uid())");expect(sql).toContain("'trip-documents','trip-documents',false,10485760");expect(sql).toContain("allowed_mime_types");});
  it("enforces same-Trip contextual links",()=>{expect(sql).toContain("foreign key(stop_id,trip_id)");expect(sql).toContain("foreign key(reservation_id,trip_id)");expect(sql).toContain("foreign key(travel_leg_id,trip_id)");});
  it("generates random object keys and re-validates uploaded content on the server",()=>{expect(forms).toContain("${crypto.randomUUID()}.${extensionFor(mime)}");expect(forms).toContain("upsert: false");expect(actions).toContain("const prefix = `${user.id}/${tripId}/${documentId}/`");expect(actions).toContain("!objectPath.startsWith(prefix)");expect(actions).toContain("inspectUpload(blob)");expect(actions).not.toContain("service_role");expect(forms).not.toContain("service_role");});
  it("authorizes each download and issues only a 60-second URL",()=>{expect(download).toContain("getOwnedDocument(tripId,documentId)");expect(download).toContain("createSignedUrl(document.attachmentPath,60");expect(download).toContain('"Cache-Control","private, no-store');});
  it("requires server-side destructive confirmation",()=>{expect(actions).toContain('data.get("confirmation")');expect(actions).toContain('data.get("confirm") !== "remove"');});
});
