import { describe,expect,it } from "vitest";import { buildTripDays,compareItems,generateDateRange,overlappingItemIds } from "@/features/itinerary/days";import { itinerarySchema } from "@/features/itinerary/schemas";import type { ItineraryItem } from "@/features/itinerary/types";import type { Trip } from "@/features/trips/types";
const item=(overrides:Partial<ItineraryItem>={}):ItineraryItem=>({id:"10000000-0000-4000-8000-000000000001",tripId:"t1",tripDate:"2026-09-02",stopId:null,title:"Museu",placeName:null,startLocalTime:null,endLocalTime:null,timezone:null,notes:null,sortOrder:1000,status:"active",createdAt:"",updatedAt:"",...overrides});
const trip:Trip={id:"t1",userId:"u1",name:"Europa",startDate:"2026-09-01",endDate:"2026-09-15",originLabel:null,returnLabel:null,travelersCount:1,baseCurrency:"EUR",targetBudgetMinor:null,archivedAt:null,createdAt:"",updatedAt:""};
const valid={tripDate:"2026-09-02",stopId:"",title:"Louvre",placeName:"Museu do Louvre",startTime:"09:30",endTime:"12:30",timezone:"Europe/Paris",notes:"Bilhete",requestId:"20000000-0000-4000-8000-000000000001"};
describe("daily itinerary",()=>{
 it("generates inclusive Trip days including single-day Trips",()=>{expect(generateDateRange("2026-09-01","2026-09-15")).toHaveLength(15);expect(generateDateRange("2026-09-01","2026-09-01")).toEqual(["2026-09-01"]);expect(buildTripDays(trip,[],[],[])).toHaveLength(15);});
 it("keeps untimed items distinct and sorts timed items chronologically",()=>{const items=[item({id:"u",sortOrder:1}),item({id:"late",startLocalTime:"18:00",timezone:"Europe/Paris"}),item({id:"early",startLocalTime:"09:00",timezone:"Europe/Paris"})].sort(compareItems);expect(items.map(i=>i.id)).toEqual(["early","late","u"]);expect(items[2].startLocalTime).toBeNull();});
 it("detects only deterministic interval overlaps",()=>{const overlapping=[item({id:"a",startLocalTime:"10:00",endLocalTime:"12:00",timezone:"Europe/Paris"}),item({id:"b",startLocalTime:"11:30",endLocalTime:"13:00",timezone:"Europe/Paris"}),item({id:"c",startLocalTime:"11:00",endLocalTime:null,timezone:"Europe/Paris"})];expect([...overlappingItemIds(overlapping)].sort()).toEqual(["a","b"]);});
 it("accepts equal times and rejects end without start or end before start",()=>{expect(itinerarySchema.safeParse({...valid,endTime:"09:30"}).success).toBe(true);expect(itinerarySchema.safeParse({...valid,startTime:"",endTime:"12:00",timezone:""}).success).toBe(false);expect(itinerarySchema.safeParse({...valid,startTime:"14:00",endTime:"13:00"}).success).toBe(false);});
 it("rejects blank titles, invalid Stops and invalid timezone; timezone is optional",()=>{expect(itinerarySchema.safeParse({...valid,title:"   "}).success).toBe(false);expect(itinerarySchema.safeParse({...valid,stopId:"foreign"}).success).toBe(false);expect(itinerarySchema.safeParse({...valid,timezone:""}).success).toBe(true);expect(itinerarySchema.safeParse({...valid,timezone:"GMT+2"}).success).toBe(false);});
 it("preserves free text as plain values",()=>{const parsed=itinerarySchema.parse({...valid,title:"<script>alert(1)</script>",notes:"<b>texto</b>"});expect(parsed.title).toBe("<script>alert(1)</script>");expect(parsed.notes).toBe("<b>texto</b>");});
});
