import { describe,expect,it } from "vitest";import { affectedLegsForOrder,buildAdjacencies,buildRoutePoints,parseRoutePointToken,validateStopSequence } from "@/features/route/route-model";import { legSchema,stopSchema } from "@/features/route/schemas";import { zonedDateTimeToEpoch } from "@/features/route/time";import type { Stop,TravelLeg } from "@/features/route/types";
const request="8cbbb5e9-2f75-44ce-b327-94f289514303";const stop=(id:string,position:number,arrivalDate:string,departureDate:string):Stop=>({id,tripId:"trip",position,placeName:id,countryCode:"PT",countryName:"Portugal",arrivalDate,departureDate,timezone:"Europe/Lisbon",notes:null,createdAt:"",updatedAt:""});
const a=stop("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",1,"2026-11-01","2026-11-03"),b=stop("bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",2,"2026-11-03","2026-11-05"),c=stop("cccccccc-cccc-4ccc-8ccc-cccccccccccc",3,"2026-11-06","2026-11-08");
const leg=(from:string,to:string):TravelLeg=>({id:"leg",tripId:"trip",fromKind:"stop",fromStopId:from,toKind:"stop",toStopId:to,mode:"train",status:"booked",departureDate:null,departureTime:null,departureTimezone:null,arrivalDate:null,arrivalTime:null,arrivalTimezone:null,operator:null,reference:null,priceMinor:null,priceCurrency:null,notes:null,reviewRequired:false});
describe("stops",()=>{it("accepts a first and same-day Stop",()=>{expect(stopSchema.safeParse({placeName:"Paris",countryCode:"fr",countryName:"França",arrivalDate:"2026-11-02",departureDate:"2026-11-02",timezone:"Europe/Paris",notes:"",createRequestId:request}).success).toBe(true)});it("rejects departure before arrival",()=>expect(stopSchema.safeParse({placeName:"Paris",countryCode:"FR",countryName:"França",arrivalDate:"2026-11-03",departureDate:"2026-11-02",timezone:"",notes:"",createRequestId:request}).success).toBe(false));it("allows gaps and rejects overlaps",()=>{expect(validateStopSequence([a,b,c])).toBeNull();expect(validateStopSequence([a,{...b,arrivalDate:"2026-11-02"}])).toContain("sobrepõem")});it("allows duplicate cities",()=>expect(validateStopSequence([a,{...b,placeName:a.placeName}])).toBeNull())});
describe("route ordering and reconciliation",()=>{it("builds boundaries separately from Stops",()=>expect(buildRoutePoints({originLabel:"Lisboa",returnLabel:"Porto"},[a]).map(p=>p.kind)).toEqual(["origin_boundary","stop","return_boundary"]));it("marks a booked Leg affected without retargeting",()=>{const booked=leg(a.id,b.id);expect(affectedLegsForOrder([b,a,c],[booked])).toEqual([booked])});it("does not let cancelled Legs satisfy adjacency",()=>{const points=buildRoutePoints({originLabel:null,returnLabel:null},[a,b]);expect(buildAdjacencies(points,[{...leg(a.id,b.id),status:"cancelled"}])[0].activeLeg).toBeNull()});it("parses only valid route point tokens",()=>{expect(parseRoutePointToken(`stop:${a.id}`)?.stopId).toBe(a.id);expect(parseRoutePointToken("stop:bad")).toBeNull()})});
describe("travel times and price",()=>{const base={fromToken:`stop:${a.id}`,toToken:`stop:${b.id}`,mode:"plane",status:"planned",departureDate:"2026-11-01",departureTime:"09:00",departureTimezone:"Europe/Lisbon",arrivalDate:"2026-11-01",arrivalTime:"12:00",arrivalTimezone:"Europe/Paris",operator:"",reference:"",priceAmount:"45",priceCurrency:"GBP",notes:"",createRequestId:request};it("compares cross-timezone instants",()=>{expect(zonedDateTimeToEpoch("2026-11-01","09:00","Europe/Lisbon")).toBeLessThan(zonedDateTimeToEpoch("2026-11-01","12:00","Europe/Paris")!);expect(legSchema.safeParse(base).success).toBe(true)});it("rejects impossible travel; timezone is optional",()=>{expect(legSchema.safeParse({...base,arrivalTime:"07:00"}).success).toBe(false);expect(legSchema.safeParse({...base,departureTimezone:""}).success).toBe(true);expect(legSchema.safeParse({...base,departureTimezone:"GMT+2"}).success).toBe(false)});it("allows missing exact times",()=>expect(legSchema.safeParse({...base,departureTime:"",departureTimezone:"",arrivalTime:"",arrivalTimezone:""}).success).toBe(true));it("preserves original price currency and rejects negatives",()=>{expect(legSchema.parse(base).priceCurrency).toBe("GBP");expect(legSchema.safeParse({...base,priceAmount:"-1"}).success).toBe(false)})});

describe("approved country code expansion",()=>{it("accepts two to four letters and rejects values outside that range",()=>{const input={placeName:"Lisboa",countryName:"Portugal",arrivalDate:"2026-11-02",departureDate:"2026-11-02",timezone:"Europe/Lisbon",notes:"",createRequestId:request};for(const countryCode of ["PT","PRT","PORT"]){expect(stopSchema.safeParse({...input,countryCode}).success).toBe(true)}expect(stopSchema.safeParse({...input,countryCode:"P"}).success).toBe(false);expect(stopSchema.safeParse({...input,countryCode:"PORTU"}).success).toBe(false)})});
