import { describe,expect,it } from "vitest";import { calculateSavingsPlan,calendarDaysBetween,ceilDivide,formatProgress } from "@/features/savings/calculations";import { availableMinor,savingsFormSchema } from "@/features/savings/schemas";import type { SavingsPlanInput } from "@/features/savings/types";
const input=(overrides:Partial<SavingsPlanInput>={}):SavingsPlanInput=>({targetBudgetMinor:"300000",forecastMinor:"260000",hasForecast:true,netPaidMinor:"30000",currentAvailableMinor:"70000",startDate:"2026-12-10",today:"2026-09-01",...overrides});
describe("savings plan",()=>{
 it("prefers target budget; payments are spent from what we have, never added to it",()=>{const result=calculateSavingsPlan(input());expect(result.targetBasis).toBe("target_budget");expect(result.targetMinor).toBe(300000n);expect(result.totalFundedMinor).toBe(70000n);expect(result.eligiblePaidMinor).toBe(30000n);expect(result.remainingMinor).toBe(230000n);expect(result.state).toBe("partially_funded");});
 it("falls back to a priced forecast",()=>{const result=calculateSavingsPlan(input({targetBudgetMinor:null}));expect(result.targetBasis).toBe("current_forecast");expect(result.targetMinor).toBe(260000n);});
 it("distinguishes no target from an explicit zero target",()=>{expect(calculateSavingsPlan(input({targetBudgetMinor:null,hasForecast:false})).state).toBe("no_target");const zero=calculateSavingsPlan(input({targetBudgetMinor:"0",netPaidMinor:"0",currentAvailableMinor:"0"}));expect(zero.state).toBe("fully_funded");expect(zero.progressBasisPoints).toBe(10000n);});
 it("floors negative net paid and never counts actual expense input",()=>{const result=calculateSavingsPlan(input({netPaidMinor:"-2000",currentAvailableMinor:"0"}));expect(result.eligiblePaidMinor).toBe(0n);expect(result.totalFundedMinor).toBe(0n);expect(result.state).toBe("not_funded");});
 it("shows fully funded and overfunded without exceeding 100 percent",()=>{expect(calculateSavingsPlan(input({targetBudgetMinor:"100000",currentAvailableMinor:"100000"})).state).toBe("fully_funded");const over=calculateSavingsPlan(input({targetBudgetMinor:"100000",currentAvailableMinor:"130000"}));expect(over.state).toBe("overfunded");expect(over.surplusMinor).toBe(30000n);expect(over.progressBasisPoints).toBe(10000n);});
 it("handles departure today and passed dates without division",()=>{const today=calculateSavingsPlan(input({startDate:"2026-09-01"})),past=calculateSavingsPlan(input({startDate:"2026-08-31"}));expect(today.state).toBe("departure_today");expect(today.dailyPaceMinor).toBeNull();expect(past.state).toBe("trip_started_or_past");expect(past.monthlyPaceMinor).toBeNull();});
 it("rounds each recommendation upward using exact integer formulas",()=>{const result=calculateSavingsPlan(input({targetBudgetMinor:"100001",netPaidMinor:"0",currentAvailableMinor:"0",startDate:"2026-12-10"}));expect(result.daysUntilDeparture).toBe(100);expect(result.dailyPaceMinor).toBe(1001n);expect(result.weeklyPaceMinor).toBe(7001n);expect(result.monthlyPaceMinor).toBe(30438n);expect(ceilDivide(10001n,1000n)).toBe(11n);});
 it("uses calendar dates across leap day and timezone-independent boundaries",()=>{expect(calendarDaysBetween("2028-02-28","2028-03-01")).toBe(2);expect(calendarDaysBetween("2026-12-31","2027-01-01")).toBe(1);});
 it("formats deterministic progress",()=>{expect(formatProgress(3333n)).toBe("33,33%");expect(formatProgress(10000n)).toBe("100%");});
 it("validates non-negative base-currency money and request IDs",()=>{expect(availableMinor("0","EUR")).toBe(0n);expect(availableMinor("-1","EUR")).toBeNull();expect(savingsFormSchema.safeParse({currentAvailable:"10",currency:"GBP",requestId:"20000000-0000-4000-8000-000000000001"}).success).toBe(true);expect(savingsFormSchema.safeParse({currentAvailable:"10",currency:"EURO",requestId:"bad"}).success).toBe(false);});
});
